export const Employees = [
  {
    id: 1,
    name: 'Suraj',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'JavaScript',
    textEditors: ['Atom', 'Sublime Text','Notepad++'],
  },
  {
    id: 2,
    name: 'Sunil',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text','Notepad++'],
  },
  {
    id: 3,
    name: 'Ramesh',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 4,
    name: 'Akhil',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'JavaScript',
    textEditors: ['Atom', 'Sublime Text','Notepad++'],
  },
  {
    id: 5,
    name: 'Vivek',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 6,
    name: 'Deepu',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'Java',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 7,
    name: 'Hitesh',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 8,
    name: 'Anhishek',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'Java',
    textEditors: ['Atom', 'Sublime Text','Notepad++'],
  },
  {
    id: 9,
    name: 'Joshi',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 10,
    name: 'Saurab',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'JavaScript',
    textEditors: ['Atom', 'Sublime Text','Notepad++'],
  },
  {
    id: 11,
    name: 'Nikhil',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'Java',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 12,
    name: 'Swaroop',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'Java',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 13,
    name: 'Avinash',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 14,
    name: 'Chetan',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'JavaScript',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 15,
    name: 'Bharghav',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text'],
  },
  {
    id: 16,
    name: 'Ramu',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'C++',
    textEditors: ['Atom', 'Sublime Text','Notepad++'],
  },
  {
    id: 17,
    name: 'Prince',
    address: 'India',
    gender: 'M',
    description: 'Test 123',
    langauage: 'JavaScript',
    textEditors: ['Atom', 'Sublime Text','Notepad++'],
  },
];
